### PR TITLE
Spec 0.3.5

### PR DESCRIPTION
**Pull request by definite**
This branch is currently under Fedora [package review](https://bugzilla.redhat.com/show_bug.cgi?id=2097925)

I hope to get consensus from upstream, thus I wonder that

Should we keep /usr/local/libexec and /usr/local/etc for development reference?

### CODE REVIEW

**Comment by cryptomilk** [comment]
For the `data_files` if you use relative paths then it will take the --prefix into account:

Example:
https://github.com/jupyter/notebook/pull/6010/files

**Comment by definite** [comment]
@cryptomilk 

Um, since we have following directories:

- /etc/
- /usr/libexec/certmonger

I don't think there is a common prefix that make sense. 

Can I use my pull request to replace 

/usr/local/etc -> /etc
/usr/local/libexec -> /usr/libexec

**Comment by cryptomilk** [comment]
See e.g.

https://stackoverflow.com/questions/10456279/python-setuptools-how-to-include-a-config-file-for-distribution-into-prefix-e

Maybe you should remove the example confgurations from data_files and do not install them with setuptools at all.

**Comment by dmulder** [comment]
@cryptomilk Can you review the most recent changes here? We use a totally different spec file at SUSE, so I'm not the person to review this mr.

**Comment by cryptomilk** [comment]
I would suggest to not ship a spec file at all. The part to setup.py looks fine for me.

**Comment by dmulder** [comment]
Sounds good to me.

**Pull request closed without merging**
