### PR TITLE
Migrate from setup.py to pyproject

### PR DESCRIPTION
**Pull request by cryptomilk**
Migrate from setup.py to pyproject.toml

### CODE REVIEW

**Comment by cryptomilk** [comment]
@dmulder do you prefer setuptools or pdm?

**Comment by dmulder** [comment]
> @dmulder do you prefer setuptools or pdm?

I've never even heard of pdm. I have no preference.

**Comment by cryptomilk** [comment]
I got it sorted out. I also added a tox.ini filed and use gh-actions for running tox now.

**Comment by cryptomilk** [comment]
Check the tests output, it runs test for several python versions now.

**Comment by cryptomilk** [comment]
We could also enable linting and type checking if you want.

**Review by dmulder — APPROVED** [review]
LGTM!

**Comment by dmulder** [comment]
@cryptomilk I granted you write access to the repo, so feel free to merge when ready.

**Pull request merged**
